import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import React, { ReactNode } from 'react';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the props interface
interface LayoutProps {
  children: ReactNode; // Specify that children is of type ReactNode
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <div>
          {/* Your layout components like Header, Footer, etc. */}
          {children} {/* This will render the page content */}
        </div>
      </body>
    </html>
  );
};

export default Layout;
